### GET request to example server
POST https://d7a2-73-71-109-237.ngrok-free.app/swapCacheIds
Content-Type: application/json

{
  "oldSessionCacheId": "Outbound-1724820416820",
  "newSessionCacheId": "ff65fdff-b1b8-4a4e-994a-cda232611f48"
}

###
